import './globals.css';
import { Urbanist } from 'next/font/google';
import Footer from '../components/footer';
import Navbar from '../components/navbar';

const urbanist = Urbanist({ subsets: ['latin'] });

export const metadata = {
  title: 'Nyanga Travel',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
